export * from './user'
export * from "./testType"
export * from "./show"
export * from "./grade"
export * from "./identityData"
export * from "./delTeacher"
export * from "./addTeacher"
export * from "./delStudent"
export * from "./searchStu"
